// <auto-generated />
using System;
using LogService.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LogService.Migrations
{
    [DbContext(typeof(LogServiceContext))]
    [Migration("20190126142322_Initialize")]
    partial class Initialize
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LogServiceModels.LogEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Level");

                    b.Property<string>("LogMessage")
                        .IsRequired();

                    b.Property<DateTime>("LoggingTime");

                    b.Property<string>("Sender")
                        .IsRequired();

                    b.Property<DateTime?>("SentTime")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("LogsEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
